{"uuid": "813f6a40-e980-43c3-95b8-0249753c590a", "children": ["32ba29ae-6db3-489d-a42d-34a6287f2e6f"], "befores": [{"name": "setup_and_teardown", "status": "passed", "start": 1712640498933, "stop": 1712640501759}], "afters": [{"name": "setup_and_teardown::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\Dheerendra\\PycharmProjects\\NewProject\\Python_Hybrid_Project\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dheerendra\\PycharmProjects\\NewProject\\Python_Hybrid_Project\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 922, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Dheerendra\\PycharmProjects\\NewProject\\Python_Hybrid_Project\\tests\\conftest.py\", line 37, in setup_and_teardown\n    driver.quit()\n  File \"C:\\Users\\Dheerendra\\PycharmProjects\\NewProject\\Python_Hybrid_Project\\.venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 188, in quit\n    self.service.stop()\n  File \"C:\\Users\\Dheerendra\\PycharmProjects\\NewProject\\Python_Hybrid_Project\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 146, in stop\n    self.send_remote_shutdown_command()\n  File \"C:\\Users\\Dheerendra\\PycharmProjects\\NewProject\\Python_Hybrid_Project\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 131, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dheerendra\\PycharmProjects\\NewProject\\Python_Hybrid_Project\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 120, in is_connectable\n    return utils.is_connectable(self.port)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dheerendra\\PycharmProjects\\NewProject\\Python_Hybrid_Project\\.venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dheerendra\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\socket.py\", line 844, in create_connection\n    exceptions.clear()  # raise only the last error\n    ^^^^^^^^^^^^^^^^^^\n"}, "start": 1712640502025, "stop": 1712640504145}], "start": 1712640498933, "stop": 1712640504145}